### ISSUE TITLE
[Roadmap] Paragon V1

### ISSUE THREAD

**Issue by KCarretto** [KCarretto/paragon#112]
# P0
- [x] Worker
    - [x] ssh/exec
    - [x] ssh/sendFile
    - [x] ssh/recvFile
    - [x] PubSub

- [x] Pagination

# P1
- [ ] Notifications
- [ ] RedLight
- [x] CDN

# P2 
- [ ] News Feed
- [x] Script Editor

# P3 
- [ ] Build Service
- [x] Flow / TypeScript
- [ ] Scanner

**Comment by Cictrone** [comment]
Pagination complete
Script Editor complete
