### ISSUE TITLE
Add some Functions to sys package

### ISSUE THREAD

**Issue by Cictrone** [KCarretto/paragon#16]
- [x] move
- [ ] chattr
- [x] remove
- [x] copy
- [x] exec
- [x] read
- [ ] lsattr
- [x] write
- [x] chmod
- [ ] ssh
- [x] chown
- [x] list processes
- [x] list network connections
- [x] cURL
- [x] kill
- [x] list directory entries
- [x] regex replace string
- [x] spawn Process
- [ ] timestomp

**Comment by KoalaTea** [comment]
yw

**Comment by KoalaTea** [comment]
but are they tested?

**Comment by KoalaTea** [comment]
is dd different from write for example floppy birding?
