### ISSUE TITLE
Feature: Add CSV Upload forms for Targets and Credentials

### ISSUE THREAD

**Issue by micahjmartin** [KCarretto/paragon#205]
The Create Target Form

![image](https://user-images.githubusercontent.com/15130760/74054643-5f485580-49ac-11ea-87e5-22ee67826d91.png)

and Add Credentials form
![image](https://user-images.githubusercontent.com/15130760/74054711-830b9b80-49ac-11ea-873a-79a1311d8f7e.png)

Could have a small link in the corner that allows for bulk uploading creds/targets via CSV files. This will allow for other tools to easily integrate

**Comment by KoalaTea** [comment]
Hey @micahjmartin is this how https://github.com/RITRedteam/Topology-Generator outputs? That was what I was going to use as the integration point. Especially easy if whiteteam uses it at all

**Comment by micahjmartin** [comment]
Topo Generator outputs something like this: https://github.com/RITRedteam/Topology-Generator/blob/master/topos/ists_17.json

We could integrate that functionality into Paragon though and have all the tools be able to pull the topo from a hosted version on paragon. That could be nice. If not I was going to make topogen output CSV

**Comment by KoalaTea** [comment]
I think standardizing on that is the way to go, do any other tools use it right now?

**Comment by micahjmartin** [comment]
Yes I have several tools that use that json format including the pwnboard
and elk infra
