### ISSUE TITLE
Backend Graphql Support

### ISSUE THREAD

**Issue by KCarretto** [KCarretto/paragon#58]
# Summary
Create a GraphQL server endpoint capable of processing graphql queries for the models defined by ent schemas and compliant with the relay spec.

# Requirements

- [ ] Ent Schemas -> Models -> GraphQLServer w/ Relay Compatibility
- [ ] /graphql endpoint for queries
- [ ] /graphiql for testing & debug

# References
* [Thunder](https://github.com/samsarahq/thunder) (Reflect Based)
* [GQLGen](https://github.com/99designs/gqlgen) (Code generation)
* [GraphQL-Go-Relay](https://github.com/graphql-go/relay) (Relay helpers if needed)
* [Relay Spec](https://relay.dev/docs/en/graphql-server-specification)

**Comment by Cictrone** [comment]
Made a JSON RPC API in #60 that @KoalaTea is gunna use with Apollo Server.
